# Consuming a Swapi Client

Remember that by default Swapi Clients are using Superagent under the hood to handle network requests and some of the Superagent API is exposed through Swapi. Getting familiar with Superagent will help you understand Swapi Client behavior. Find the docs here: [http://visionmedia.github.io/superagent/](http://visionmedia.github.io/superagent/)

## Handling Responses

Superagent is opinionated in how it handles different status codes. 4xx, 5xx and network errors are all exposed via an error object. Look `err.status` to determine the statusCode. Look at `err.errObj.errno` to find network errors.

Superagent docs also have a section on Error Handling that is helpful. Note that the `response` object documented in Superagent is actually found at `err.errObj.response` not `err.response`.

```js
const getAReallyCoolThing = function (req, thingId) {
  const someSwapiClient = req.app.services.someSwapiClient;

  if (!req || !thingId) {
    return Promise.reject(new Error('req and thingId both required'));
  }

  if (!someSwapiClient) {
    return Promise.reject(new Error('swapi client not found'));
  }

  return someSwapiClient.withMeta(req)
    .getAReallyCoolThing({ thingId: 123 })
    .then((response) => {

      const thing = _.get(response.obj.payload.data);
      if (response.statusCode === 200 && thing) {
        return thing;
      }

      throw new Error("unexpected api response");
    })
    .catch((err) => {
      const statusCode = err.code;
      const networkErrCode = _.get(err.errObj.errno);

      // your statusCode logic handlers
      if (statusCode === 500) {
        throw new myCustomDownstreamServiceErr();
      }

      if (statusCode === 404) {
        throw new myCustomNotFoundErr();
      }

      // your network error logic handlers
      if (networkErrCode === ENOTFOUND) {
        throw new Error('ENOTFOUND');
      }

      // finally rethrow the error if you don't have custom logic for it
      throw err;
    });
  };
```

If you don't need to handle any errors than just skip the `catch` block and whatever is consuming your promise chain can deal with it (or not and it will be caught by Hapi eventually).


## Network Errors

Expect `err.errObj.errno` to be:
* `ETIME` - Absolute timeout exceeded from `timeout`. For example server started but did not finish sending data would trigger this.
* `ETIMEDOUT` - No response from server before `responseTimeout`
* `ENOTFOUND` - hostname doesn't resolve
* ... other OS based network errors can be looked up elsewhere.
